import mongoose from "mongoose";
const jobSchema=mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    jobType:{
        type:String,
        required:true,
        enum:["Full-time","Part-time"]
    },
    company:{
        type:String,
        required:true
    },
    location:{
        type:String,
        required:true
    },
    introduction:{
        type:String,
    },
    qualification:{
        type:String,
        required:true
    },
    offers:{
        type:String,
    },
    salary:{
        type:String,
        required:true
    },
    personalWebsite:{
        type:String,
        url:String
    },
    hiringMultipleCandidates:{
        type:String,
        default:"No",
        enum:["Yes","No"]
    },
    jobNiche:{
        type:String,
        required:true
    },
    newsLetterSend:{
        type:String,
        default:false
    },
    jobPostedOn:{
        type:String,
        default:Date.now()
    },
    postedBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    }
})
export const Job=mongoose.model("job",jobSchema)